--
-- cleanup
DROP TYPE "T_ARIMA_FORE_RESULTS";
DROP TABLE "SIGNATURE_ARIMA_FORE";
DROP TYPE "T_ARIMA_PARAMS";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP" ('TECH_ANALYSIS','P_ARIMA_FORE');
--DROP TABLE "TS_RESULTS";
--DROP VIEW "V_TS_RESULTS";

-- PAL setup
CREATE TYPE "T_ARIMA_FORE_RESULTS" AS TABLE("ID" INTEGER, "Net" DOUBLE, "LOW80" DOUBLE, "HI80" DOUBLE, "LOW95" DOUBLE, "HI95" DOUBLE);
CREATE TYPE "T_ARIMA_PARAMS" AS TABLE ("NAME" VARCHAR(50), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE COLUMN TABLE "SIGNATURE_ARIMA_FORE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE_ARIMA_FORE" VALUES (1, 'TECH_ANALYSIS', 'ARIMA_TEST_MODEL', 'IN');
INSERT INTO "SIGNATURE_ARIMA_FORE" VALUES (2, 'TECH_ANALYSIS', 'T_ARIMA_PARAMS', 'IN');
INSERT INTO "SIGNATURE_ARIMA_FORE" VALUES (3, 'TECH_ANALYSIS', 'T_ARIMA_FORE_RESULTS', 'OUT');


CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL','ARIMAFORECAST','TECH_ANALYSIS','P_ARIMA_FORE','SIGNATURE_ARIMA_FORE');

CREATE COLUMN TABLE ARIMA_TEST_RESULTS LIKE T_ARIMA_FORE_RESULTS;

-- app runtime
DROP TABLE #TS_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #TS_PARAMS LIKE T_ARIMA_PARAMS;

INSERT INTO #TS_PARAMS VALUES ('ForecastLength', 12, null, null);

TRUNCATE TABLE ARIMA_TEST_RESULTS;

CALL P_ARIMA_FORE (ARIMA_MODEL, "#TS_PARAMS", ARIMA_TEST_RESULTS) WITH OVERVIEW;


drop view V_ARIM_PREDICTIONS;
create view V_ARIM_PREDICTIONS as 
  select case when  a."ID" is not null then a."ID" else b."ID" end as "ID",
       a."Net", 
       b."NET" as "Predicted Net",
       b."LOW80",
       b."HI80", 
       b."LOW95", 
       b."HI95"
   from PH3_ARIMA_DATA_TRAIN  as a
    full join  ARIMA_TEST_RESULTS as b
    on a."ID" = b."ID";
    
    select count(*) from ARIMA_TEST_RESULTS;
    select count(*) from PH3_ARIMA_DATA_TRAIN;
    select count(*) from  V_ARIM_PREDICTIONS;

