  -- cleanup--
DROP TYPE "T_PH3_ARIMA_DATA";
DROP TYPE "T_ARIMA_PARAMS";
DROP TYPE "ARIMA_TEST_MODEL";
DROP TABLE "ARIMA_SIGNARTURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('TECH_ANALYSIS', 'P_ARIMA');
drop view V_PH3_ARIMA_DATA_TRAIN;
DROP TABLE "ARIMA_MODEL";

-- procedure setup
CREATE TYPE "T_PH3_ARIMA_DATA" AS TABLE ("ID" INTEGER, "Net" DOUBLE);
CREATE TYPE "T_ARIMA_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "ARIMA_TEST_MODEL" AS TABLE ("NAME" VARCHAR(60), "VALUE" VARCHAR(5000));

CREATE COLUMN TABLE "ARIMA_SIGNARTURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "ARIMA_SIGNARTURE" VALUES (1, 'TECH_ANALYSIS', 'T_PH3_ARIMA_DATA', 'IN');
INSERT INTO "ARIMA_SIGNARTURE" VALUES (2, 'TECH_ANALYSIS', 'T_ARIMA_PARAMS', 'IN');
INSERT INTO "ARIMA_SIGNARTURE" VALUES (3, 'TECH_ANALYSIS', 'ARIMA_TEST_MODEL', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'ARIMATRAIN', 'TECH_ANALYSIS', 'P_ARIMA', "ARIMA_SIGNARTURE");

-- data setup
CREATE COLUMN TABLE "ARIMA_MODEL" LIKE "ARIMA_TEST_MODEL";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_ARIMA_PARAMS";
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO "#PARAMS" VALUES ('METHOD', 1, null, null); -- 0: conditional sum squares, 1: max likelihood estimation
--INSERT INTO "#PARAMS" VALUES ('STATIONARY', 1, null, null); -- 0: result may not be stationary, 1: is stationary
--INSERT INTO "#PARAMS" VALUES ('P', 1, null, null); -- Auto Regression
--INSERT INTO "#PARAMS" VALUES ('D', 0, null, null); -- Differentiation
--INSERT INTO "#PARAMS" VALUES ('Q', 1, null, null); -- Moving Average
INSERT INTO "#PARAMS" VALUES ('SEASONAL_P', 1, null, null); -- Seasonal Auto Regression
INSERT INTO "#PARAMS" VALUES ('SEASONAL_D', 1, null, null); -- Seasonal Differentiation
INSERT INTO "#PARAMS" VALUES ('SEASONAL_Q', 1, null, null); -- Seasonal Moving Average
INSERT INTO "#PARAMS" VALUES ('SEASONAL_PERIOD', 3, null, null); -- Seasonal Period

TRUNCATE TABLE "ARIMA_MODEL";

--insert into  PH3_ARIMA_DATA_TRAIN select top 10 "ID","Net" from "_SYS_BIC"."dbag_analytics.models/cv_market" 
--where ( "ID_CALENDAR" >='1' and "ID_CALENDAR" <= '10' ) and "PH3" = 'CB0100105';

CALL "P_ARIMA" ( PH3_ARIMA_DATA_TRAIN, "#PARAMS", ARIMA_MODEL) WITH OVERVIEW;

SELECT * FROM "ARIMA_MODEL";

select count(*) from PH3_ARIMA_DATA_TRAIN;
