-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS_ST";
DROP TYPE "T_RANDOM";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('TECH_ANALYSIS', 'P_ST');

DROP TABLE "RESULTS";
DROP TABLE "RANDOM";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "NET" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS_ST" AS TABLE ("CYCLE_LENGTH" INTEGER, "SEASONALITY_MODE" VARCHAR(60));
CREATE TYPE "T_RANDOM" AS TABLE ("ID" INTEGER, "VALUE" DOUBLE);



CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'TECH_ANALYSIS', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'TECH_ANALYSIS', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'TECH_ANALYSIS', 'T_RESULTS_ST', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'TECH_ANALYSIS', 'T_RANDOM', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'SEASONALITYTEST', 'TECH_ANALYSIS', 'P_ST', "SIGNATURE");



-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('ALPHA', null, 0.2, null); -- Threshold for auto-correlation coefficient


--CALL "P_ST" ("V_DATA", "#PARAMS", "RESULTS", "RANDOM") WITH OVERVIEW;

