-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS_WNT";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('TECH_ANALYSIS', 'P_WNT');


-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "NET" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS_WNT" AS TABLE ("NAME" VARCHAR(60), "WHITENOISE" INTEGER);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'TECH_ANALYSIS', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'TECH_ANALYSIS', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'TECH_ANALYSIS', 'T_RESULTS_WNT', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'WHITENOISETEST', 'TECH_ANALYSIS', 'P_WNT', "SIGNATURE");

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO "#PARAMS" VALUES ('LAG', 2, null, null);
--INSERT INTO "#PARAMS" VALUES ('PROBABILITY', null, 0.9, null);


--CALL "P_WNT" ("V_DATA", "#PARAMS", "RESULTS") WITH OVERVIEW;

